/*
 * Copyright 2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.springaicommunity.watsonx.chat.message;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.springaicommunity.watsonx.chat.util.ChatRole;
import io.github.springaicommunity.watsonx.chat.util.ToolType;
import java.util.List;

/**
 * Base class for chat messages in a conversation for watsonx.ai.
 *
 * @param role The role of the message sender (e.g., user, assistant, system, tool).
 * @param name An optional name for the participant. Provides the model information to differentiate
 *     between participants of the same role.
 * @param textChatUserContent The content of the message, which can be text or structured data.
 * @param refusal An optional refusal message by the assistant.
 * @param toolCalls The tool calls generated by the model, such as function calls.
 * @param toolCallId The tool call ID associated with this message.
 * @author Tristan Mahinay
 * @since 1.1.0-SNAPSHOT
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TextChatMessage(
    @JsonProperty("role") ChatRole role,
    @JsonProperty("name") String name,
    @JsonProperty("content") Object textChatUserContent,
    @JsonProperty("refusal") String refusal,
    @JsonProperty("tool_calls") List<TextChatToolCall> toolCalls,
    @JsonProperty("tool_call_id") String toolCallId) {

  /**
   * Constructor for an assistant message.
   *
   * @param content The content of the message.
   * @param name An optional name for the participant. Provides the model information to
   *     differentiate between participants of the same role.
   * @param refusal An optional refusal message by the assistant.
   * @param toolCalls The tool calls generated by the model, such as function calls.
   */
  public TextChatMessage(
      final String content,
      final String name,
      final String refusal,
      final List<TextChatToolCall> toolCalls) {
    this(ChatRole.ASSISTANT, name, content, refusal, toolCalls, null);
  }

  /**
   * Constructor for an assistant message.
   *
   * @param content The content of the message.
   * @param name An optional name for the participant. Provides the model information to
   *     differentiate between participants of the same role.
   */
  public TextChatMessage(final String content, final String name) {
    this(ChatRole.SYSTEM, name, content, null, null, null);
  }

  /**
   * Constructor for a tool message.
   *
   * @param content The content of the message.
   * @param name An optional name for the participant. Provides the model information to
   *     differentiate between participants of the same role.
   * @param toolCallId The tool call ID associated with this message.
   */
  public TextChatMessage(final String content, final String name, final String toolCallId) {
    this(ChatRole.TOOL, name, content, null, null, toolCallId);
  }

  /**
   * Constructor for a system message.
   *
   * @param content A list of user content for the message.
   * @param name An optional name for the participant. Provides the model information to
   *     differentiate between participants of the same role.
   */
  public TextChatMessage(final Object content, final String name) {
    this(ChatRole.USER, name, content, null, null, null);
  }

  /** Represents a tool call made by the model in watsonx.ai. */
  @JsonInclude(JsonInclude.Include.NON_NULL)
  public record TextChatToolCall(
      @JsonProperty("id") String id,
      @JsonProperty("type") ToolType type,
      @JsonProperty("function") TextChatFunctionCall function) {}

  /** Represents a function call made by the model in watsonx.ai. */
  @JsonInclude(JsonInclude.Include.NON_NULL)
  public record TextChatFunctionCall(
      @JsonProperty("name") String name, @JsonProperty("arguments") String arguments) {}
}
